ALTER TABLE `Notification` MODIFY `type` ENUM('SYSTEM','APPOINTMENT','REQUIREMENT','CLEARANCE','ANNOUNCEMENT','CLINIC_MESSAGE','OTHER') NOT NULL;

ALTER TABLE `AuditLog` MODIFY `action` ENUM('CREATE','UPDATE','DELETE','LOGIN','LOGOUT','LOGIN_FAILED','APPROVE','REJECT','DISPENSE','EXPORT','ARCHIVE','RESTORE','LIST_USERS','VIEW_USER','CREATE_USER','UPDATE_USER','DELETE_USER','ASSIGN_ROLE','ROLE_CHANGE','STATUS_CHANGE','PASSWORD_CHANGE','PASSWORD_RESET','SIGNUP','ACADEMIC_YEAR_CREATED','SEMESTER_CREATED','APPOINTMENT_CREATED','APPOINTMENT_CHECKED_IN','APPOINTMENT_STATUS_PENDING','APPOINTMENT_STATUS_APPROVED','APPOINTMENT_STATUS_CONFIRMED','APPOINTMENT_STATUS_COMPLETED','APPOINTMENT_STATUS_CANCELLED','APPOINTMENT_STATUS_NO_SHOW','APPOINTMENT_STATUS_RESCHEDULED','CLEARANCE_CREATED','CLEARANCE_PENDING','CLEARANCE_INCOMPLETE','CLEARANCE_FOR_REVIEW','CLEARANCE_CLEARED','CLEARANCE_REJECTED','CLEARANCE_EXPIRED','ANNOUNCEMENT_CREATED','ANNOUNCEMENT_PUBLISHED','MEDICINE_CREATED','MEDICINE_STOCKED_IN','MEDICINE_DISPENSED','EMERGENCY_CASE_CREATED','MEDICAL_CERTIFICATE_ISSUED','VACCINATION_RECORDED','HEALTH_SCREENING_RECORDED','VISIT_CREATED','VISIT_VITAL_SIGNS_RECORDED','VISIT_CONSULTATION_RECORDED','VISIT_STATUS_OPEN','VISIT_STATUS_IN_CONSULTATION','VISIT_STATUS_COMPLETED','VISIT_STATUS_CANCELLED','PATIENT_ARCHIVED','PATIENT_RESTORED','PATIENT_EMERGENCY_CONTACT_ADDED','PATIENT_HISTORY_ADDED','PATIENT_CONDITION_ADDED','PATIENT_ALLERGY_ADDED','REQUIREMENT_CREATED','REQUIREMENT_SUBMITTED','REQUIREMENT_NOT_SUBMITTED','REQUIREMENT_UNDER_REVIEW','REQUIREMENT_VERIFIED','REQUIREMENT_REJECTED','REQUIREMENT_EXPIRED','CONVERSATION_CREATED','MESSAGE_SENT','CONVERSATION_READ','CONVERSATION_RESOLVED','CONVERSATION_REOPENED','OTHER') NOT NULL;

CREATE TABLE `Conversation` (
  `id` VARCHAR(191) NOT NULL, `patientId` VARCHAR(191) NOT NULL, `subject` VARCHAR(191) NOT NULL,
  `topic` ENUM('APPOINTMENT','MEDICAL_CERTIFICATE','MEDICAL_CLEARANCE','HEALTH_REQUIREMENT','VACCINATION_RECORD','MEDICINE_PICKUP','GENERAL_CLINIC_CONCERN') NOT NULL,
  `status` ENUM('OPEN','RESOLVED','CLOSED') NOT NULL DEFAULT 'OPEN', `repliesEnabled` BOOLEAN NOT NULL DEFAULT true,
  `createdById` VARCHAR(191) NOT NULL, `relatedType` VARCHAR(191) NULL, `relatedId` VARCHAR(191) NULL,
  `resolvedAt` DATETIME(3) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL,
  INDEX `Conversation_patientId_updatedAt_idx`(`patientId`,`updatedAt`), INDEX `Conversation_status_updatedAt_idx`(`status`,`updatedAt`), PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ConversationParticipant` (
  `id` VARCHAR(191) NOT NULL, `conversationId` VARCHAR(191) NOT NULL, `userId` VARCHAR(191) NOT NULL,
  `participantType` VARCHAR(191) NOT NULL, `lastReadAt` DATETIME(3) NULL, `archivedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `ConversationParticipant_conversationId_userId_key`(`conversationId`,`userId`),
  INDEX `ConversationParticipant_userId_archivedAt_idx`(`userId`,`archivedAt`), PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ClinicMessage` (
  `id` VARCHAR(191) NOT NULL, `conversationId` VARCHAR(191) NOT NULL, `senderId` VARCHAR(191) NOT NULL,
  `content` TEXT NOT NULL, `allowReply` BOOLEAN NOT NULL DEFAULT true, `correctedAt` DATETIME(3) NULL,
  `deletedAt` DATETIME(3) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `ClinicMessage_conversationId_createdAt_idx`(`conversationId`,`createdAt`), INDEX `ClinicMessage_senderId_createdAt_idx`(`senderId`,`createdAt`), PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `Conversation` ADD CONSTRAINT `Conversation_patientId_fkey` FOREIGN KEY (`patientId`) REFERENCES `Patient`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `Conversation` ADD CONSTRAINT `Conversation_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `ConversationParticipant` ADD CONSTRAINT `ConversationParticipant_conversationId_fkey` FOREIGN KEY (`conversationId`) REFERENCES `Conversation`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ConversationParticipant` ADD CONSTRAINT `ConversationParticipant_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ClinicMessage` ADD CONSTRAINT `ClinicMessage_conversationId_fkey` FOREIGN KEY (`conversationId`) REFERENCES `Conversation`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ClinicMessage` ADD CONSTRAINT `ClinicMessage_senderId_fkey` FOREIGN KEY (`senderId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
