export enum UserRole {
  ADMINISTRATOR = 'ADMINISTRATOR',
  CLINIC_NURSE = 'CLINIC_NURSE',
  DOCTOR = 'DOCTOR',
  CLINIC_STAFF = 'CLINIC_STAFF',
  STUDENT = 'STUDENT',
  FACULTY_STAFF = 'FACULTY_STAFF',
}
