import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Award, FilePlus2, Printer } from 'lucide-react';
import { useState } from 'react';
import { PatientPicker } from '../components/PatientPicker';
import { Badge } from '../components/ui/Badge';
import { Button } from '../components/ui/button';
import { Card } from '../components/ui/card';
import { Modal } from '../components/ui/Modal';
import { ErrorState, LoadingState } from '../components/ui/States';
import { createCertificate, getCertificates, type MedicalCertificate } from '../services/api';

const certificateTypes = ['MEDICAL_CLEARANCE', 'FITNESS_FOR_SCHOOL', 'FITNESS_FOR_WORK', 'VACCINATION_CERTIFICATE', 'MEDICAL_EXEMPTION', 'OTHER'];
const immunizations = ['Hepatitis B1', 'Hepatitis B2', 'Hepatitis B3', 'Varicella 1', 'Varicella 2', 'Pneumococcal 1', 'Pneumococcal 2', 'Tetanus / Diphtheria', 'Influenza', 'MMR 1', 'MMR 2', 'Typhoid', 'Rabies'];
const blank = { patientId: '', type: 'MEDICAL_CLEARANCE', purpose: '', validUntil: '', findings: '', fitnessStatus: '', recommendations: '', followUpAt: '', referredTo: '', confinementType: '', confinementFrom: '', confinementUntil: '', physicianName: '', physicianLicenseNo: '', physicianPtrNo: '', physicianContact: '', remarks: '', requiredImmunizations: {} as Record<string, boolean> };

function CertificatePrintView({ certificate }: { certificate: MedicalCertificate }) {
  return <div id="certificate-print" className="bg-white p-8 text-sm text-slate-900">
    <div className="text-center"><p className="font-bold">BROKENSHIRE COLLEGE</p><p>Health &amp; Wellness Department · Madapo Hills, Davao City</p><h2 className="mt-5 text-xl font-bold">MEDICAL / DENTAL CERTIFICATE</h2></div>
    <div className="mt-8 flex justify-between"><span>Certificate No. <strong>{certificate.certificateNumber}</strong></span><span>Date: {new Date(certificate.issuedAt).toLocaleDateString()}</span></div>
    <p className="mt-8">This is to certify that I have examined <strong>{certificate.patient.firstName} {certificate.patient.lastName}</strong> ({certificate.patient.patientNumber}).</p>
    <section className="mt-6"><h3 className="border-b border-slate-400 pb-1 font-bold">FINDINGS</h3><p className="min-h-16 whitespace-pre-wrap py-3">{certificate.findings || 'No findings recorded.'}</p></section>
    <section className="mt-4"><h3 className="border-b border-slate-400 pb-1 font-bold">RECOMMENDATIONS</h3><p className="mt-3 font-semibold">{certificate.fitnessStatus?.replaceAll('_', ' ') || 'No fitness recommendation recorded'}</p><p className="mt-2 whitespace-pre-wrap">{certificate.recommendations || certificate.remarks || ''}</p>{certificate.referredTo && <p className="mt-2">Referred to: {certificate.referredTo}</p>}{certificate.followUpAt && <p>Follow-up: {new Date(certificate.followUpAt).toLocaleDateString()}</p>}{certificate.confinementType && <p>{certificate.confinementType} confinement: {certificate.confinementFrom ? new Date(certificate.confinementFrom).toLocaleDateString() : '—'} to {certificate.confinementUntil ? new Date(certificate.confinementUntil).toLocaleDateString() : '—'}</p>}</section>
    {Object.entries(certificate.requiredImmunizations || {}).some(([, checked]) => checked) && <section className="mt-6"><h3 className="font-bold">Requirements to complete</h3><p className="mt-2">{Object.entries(certificate.requiredImmunizations || {}).filter(([, checked]) => checked).map(([name]) => name).join(' · ')}</p></section>}
    <div className="mt-16 grid grid-cols-2 gap-12"><div><p>Purpose: {certificate.purpose}</p>{certificate.validUntil && <p>Valid until: {new Date(certificate.validUntil).toLocaleDateString()}</p>}</div><div className="border-t border-slate-500 pt-2"><p className="font-bold">{certificate.physicianName || certificate.issuedBy?.displayName || 'Examining physician'}</p>{certificate.physicianLicenseNo && <p>License No. {certificate.physicianLicenseNo}</p>}{certificate.physicianPtrNo && <p>PTR No. {certificate.physicianPtrNo}</p>}{certificate.physicianContact && <p>Contact: {certificate.physicianContact}</p>}</div></div>
  </div>;
}

export function CertificatesPage() {
  const queryClient = useQueryClient();
  const certificates = useQuery({ queryKey: ['certificates'], queryFn: getCertificates });
  const [form, setForm] = useState(blank);
  const [preview, setPreview] = useState<MedicalCertificate | null>(null);
  const create = useMutation({ mutationFn: () => createCertificate({ ...form, validUntil: form.validUntil ? new Date(form.validUntil).toISOString() : undefined, followUpAt: form.followUpAt ? new Date(form.followUpAt).toISOString() : undefined, confinementFrom: form.confinementFrom ? new Date(form.confinementFrom).toISOString() : undefined, confinementUntil: form.confinementUntil ? new Date(form.confinementUntil).toISOString() : undefined }), onSuccess: (created) => { setForm(blank); setPreview(created); void queryClient.invalidateQueries({ queryKey: ['certificates'] }); } });
  if (certificates.isLoading) return <LoadingState label="Loading medical certificates..." />;
  if (certificates.isError) return <ErrorState message="Unable to load medical certificates." />;
  const field = (key: keyof typeof blank, label: string, type = 'text') => <label><span className="field-label">{label}</span><input type={type} value={String(form[key] || '')} onChange={(event) => setForm({ ...form, [key]: event.target.value })} className="field-input" /></label>;
  return <div className="space-y-6">
    <header className="flex items-end justify-between border-b border-medical-200 pb-6"><div><p className="text-[11px] font-semibold uppercase tracking-widest text-brokenshire-600">Clinic documents</p><h1 className="mt-1 text-[26px] font-semibold tracking-tight text-medical-900">Medical / dental certificates</h1><p className="mt-1 text-[13px] text-medical-500">Record examination findings, recommendations, referrals, and fitness decisions.</p></div><Badge variant="success"><Award className="mr-1 inline h-3 w-3" />{certificates.data?.length ?? 0} issued</Badge></header>
    <Card title="Issue certificate" description="Complete the clinical certificate after examining the patient."><form className="space-y-5 p-5" onSubmit={(event) => { event.preventDefault(); if (form.patientId) create.mutate(); }}>
      <div className="grid gap-3 sm:grid-cols-2"><PatientPicker value={form.patientId} onChange={(patientId) => setForm({ ...form, patientId })}/><label><span className="field-label">Certificate type</span><select className="field-input" value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}>{certificateTypes.map((type) => <option key={type} value={type}>{type.replaceAll('_', ' ')}</option>)}</select></label>{field('purpose', 'Purpose')}{field('validUntil', 'Valid until', 'date')}</div>
      <div className="grid gap-3 sm:grid-cols-2"><label><span className="field-label">Findings</span><textarea required className="field-input min-h-24" value={form.findings} onChange={(event) => setForm({ ...form, findings: event.target.value })}/></label><label><span className="field-label">Recommendations</span><textarea className="field-input min-h-24" value={form.recommendations} onChange={(event) => setForm({ ...form, recommendations: event.target.value })}/></label></div>
      <div className="grid gap-3 sm:grid-cols-3"><label><span className="field-label">Fitness decision</span><select required className="field-input" value={form.fitnessStatus} onChange={(event) => setForm({ ...form, fitnessStatus: event.target.value })}><option value="">Select decision</option><option value="FIT">Fit to study / work / play</option><option value="TEMPORARY_CLEARANCE">Temporary clearance</option><option value="NOT_FIT">Not fit to study / work</option><option value="FIT_TO_RETURN">Fit to return</option></select></label>{field('followUpAt', 'Follow-up date', 'date')}{field('referredTo', 'Referred to')}</div>
      <div className="grid gap-3 sm:grid-cols-3"><label><span className="field-label">Confinement</span><select className="field-input" value={form.confinementType} onChange={(event) => setForm({ ...form, confinementType: event.target.value })}><option value="">None</option><option value="HOME">Home</option><option value="CLINIC">Clinic</option><option value="HOSPITAL">Hospital</option></select></label>{field('confinementFrom', 'From', 'date')}{field('confinementUntil', 'Until', 'date')}</div>
      <div><p className="field-label mb-2">Immunizations / requirements to complete</p><div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-4">{immunizations.map((name) => <label key={name} className="flex items-center gap-2 rounded-lg border border-medical-100 px-3 py-2 text-[12px]"><input type="checkbox" checked={Boolean(form.requiredImmunizations[name])} onChange={(event) => setForm({ ...form, requiredImmunizations: { ...form.requiredImmunizations, [name]: event.target.checked } })}/>{name}</label>)}</div></div>
      <div className="grid gap-3 sm:grid-cols-4">{field('physicianName', 'Physician name')}{field('physicianLicenseNo', 'License number')}{field('physicianPtrNo', 'PTR number')}{field('physicianContact', 'Contact number')}</div>
      {create.isError && <p className="text-[12px] text-rose-600">Unable to issue the certificate. Review the required fields and try again.</p>}<Button disabled={!form.patientId || create.isPending}><FilePlus2 className="h-4 w-4" />Issue certificate</Button>
    </form></Card>
    <Card title="Certificate history" description="Issued certificates and printable copies.">{certificates.data?.length ? <div className="divide-y divide-medical-100">{certificates.data.map((certificate) => <div className="flex items-center justify-between gap-3 px-5 py-4" key={certificate.id}><div><p className="text-[13px] font-semibold text-medical-900">{certificate.patient.firstName} {certificate.patient.lastName}</p><p className="mt-1 text-[11px] text-medical-500">{certificate.certificateNumber} · {certificate.type.replaceAll('_', ' ')} · {certificate.fitnessStatus?.replaceAll('_', ' ') || certificate.purpose}</p></div><Button variant="secondary" onClick={() => setPreview(certificate)}><Printer className="h-4 w-4" />View / print</Button></div>)}</div> : <p className="p-5 text-[13px] text-medical-500">No certificates issued yet.</p>}</Card>
    <Modal open={Boolean(preview)} onClose={() => setPreview(null)} title="Certificate preview" className="max-w-4xl">{preview && <><CertificatePrintView certificate={preview}/><div className="flex justify-end border-t border-medical-100 p-4 print:hidden"><Button onClick={() => window.print()}><Printer className="h-4 w-4"/>Print certificate</Button></div></>}</Modal>
  </div>;
}
